import type {Metadata} from "next";

import "../globals.css";
import {Navbar} from "@/components/ui/navbar";
import {Montserrat, Russo_One} from "next/font/google";
import {Toaster} from "sonner";
import {AuthProvider} from "@/providers/auth.provider";
import {Suspense} from "react";
import {PasswordRecoveryDialog} from "@/components/shared/password-recovery/passwordRecovery.dialog";
import {Footer} from "@/components/shared/footer/footer";
import {AppLoader} from "@/components/shared/appLoader";

const montserrat = Montserrat({
    subsets: ["latin", "cyrillic"],
    variable: "--font-montserrat",
    display: "swap",
});

const russoOne = Russo_One({
    weight: "400",
    subsets: ["latin", "cyrillic"],
    variable: "--font-russo-one",
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${russoOne.variable} antialiased min-h-screen flex flex-col`}
      >
      <main className={'flex-1'}>
          <AppLoader>
              <AuthProvider>
                  <Navbar />
                  {children}
                  <Suspense>
                      <PasswordRecoveryDialog/>
                  </Suspense>
              </AuthProvider>
              <Toaster position={'bottom-center'} richColors closeButton/>
          </AppLoader>
      </main>
      <Footer/>
      </body>
    </html>
  );
}
