import type {Metadata} from "next";

import '../globals.css'

import {Montserrat, Russo_One} from "next/font/google";
import {Header} from "@/components/shared/admin/header";

const montserrat = Montserrat({
    subsets: ["latin", "cyrillic"],
    variable: "--font-montserrat",
    display: "swap",
});

const russoOne = Russo_One({
    weight: "400",
    subsets: ["latin", "cyrillic"],
    variable: "--font-russo-one",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${montserrat.variable} ${russoOne.variable} antialiased min-h-screen flex flex-col`}
            >
                <main >
                    <Header/>
                    {children}
                </main>
            </body>
        </html>
    );
}
